using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DTO
{
    public enum Otoritas
    {
        CON_OTORITAS_ADMIN = 0,
        CON_OTORITAS_MANANG= 1,
        CON_OTORITAS_PLAFON= 2,
        CON_OTORITAS_TAPD = 3,
        CON_OTORITAS_TAPDP= 7,
        CON_OTORITAS_TAE = 3,
        CON_OTORITAS_APBD= 4,
        CON_OTORITAS_DPA= 5,
        CON_OTORITAS_PLAFONP = 6,
        CON_OTORITAS_TAEP = 7,
        CON_OTORITAS_APBDP= 8,
        CON_OTORITAS_DPAP = 9,

        CON_OTORITAS_BENDAHARAPENERIMAAN_SKPD = 11,
        CON_OTORITAS_BENDAHARAPENERIMAAN_PPKD = 12,
        CON_OTORITAS_BENDAHARAPENGELUARAN_SKPD = 13,
        CON_OTORITAS_BENDAHARAPENGELUARAN_PEMBANTU_SKPD = 14,
        CON_OTORITAS_BENDAHARAPENGELUARAN_PPKD = 15,
        CON_OTORITAS_KASDA  = 50,
        CON_OTORITAS_BUD = 60,
        CON_OTORITAS_AKUNTANSI = 70,
        CON_OTORITAS_PPK = 16,

        CON_OTORITAS_BUDTERIMASPM  = 61,
        CON_OTORITAS_BUDVERIFIKASISPM = 62,
        CON_OTORITAS_BUDCETAKSP2D  = 63,
        CON_OTORITAS_BUDSP2DONLINE = 64,

        CON_OTORITAS_BLUD = 65,
        CON_OTORITAS_BOS = 66,
        CON_OTORITAS_ASET = 80,
        CON_OTORITAS_AUDIT = 90,
        CON_OTORITAS_SUPPORT = 1000,

     }
}
